module.exports = {
  color:{
    "screen_main_bg":"#1B1B1B",
    "screen_green_bg":"#00A66B",
    "screen_title_bg":"#B7B7B7"
  },
  string:{
    "app_name":"screen",
    "screen_room_input_error_tip":"房间号和用户名不能为空",
    "screen_permission_error_tip":"用户没有允许需要的权限，加入通话失败",
    "screen_permission_overlay":"需要打开悬浮窗权限",
    "screen_start":"开始屏幕分享",
    "screen_stop":"停止屏幕分享",
    "screen_start_failed":"启动屏幕共享失败",
    "screen_username":"用户名：",
    "screen_room_id":"房间号：",
    "screen_resolution":"分辨率：1280x720",
    "screen_watch_tips":"请在其他设备上使用不同用户名进入相同的房间进行观看"
  }
}